all:
  children:
    activemq:
      hosts:
        admin.example.com:
    database:
      hosts:
        admin.example.com:
    opencast:
      hosts:
        admin.example.com:
          opencast_role: admin
        presentation.example.com:
          opencast_role: presentation
        worker1.example.com:
          opencast_role: worker
